config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  resources :stories do
  	resources :comments
  end

  resources :projects do
  	resources :comments
  end
  
  get '/profiles/:id', to: 'profiles#view', :as => :profiles_view

  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'


end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :stories
	has_and_belongs_to_many :users
 	has_many :comments, as: :commentable
 	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    authorized = false
    @project.users.each do |u|
      if(u.id == current_user.id)
        authorized = true
      end
    end

    if(!authorized)
      redirect_to root_path
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :avatar, :description, user_ids:[])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_commentitem.html.haml
.post.animated
  .sidebar
    .avatar
      %img.author{:src => "http://graph.facebook.com/#{comment.user.uid}/picture?type=square"}
    #socialize
      %a#left.social{:href => "#"}
        %i.fa.fa-eye
      %a#right.social{:href => "#"}
        %i.fa.fa-heart
      %a#centre.social{:href => "#"}
        %i.fa.fa-clock-o
  .mybox-middle
    .widget
      %span.username
        = comment.user.name
      %br
      %span.timestamp{:style => "clear:both;"}
        %i.fa.fa-clock-o
          = comment.created_at
      %br
      %span.timestamp{:style => "clear:both;"}
        %i.fa.fa-comments-o
          = comment.user.projects.count
      %br
      %span.timestamp{:style => "clear:both;"}
        %i.fa.fa-eye
          22 subscribers
    .message
      = comment.content

app/views/projects/_comments.html.haml
.container
  %div.row{ :id => "comments"}
    - @project.comments.each do |comment|
      = render 'commentitem', :comment => comment
    .entry{:id => "new_comment"}
      .sidebar
        .avatar
          %img.author{:src => "http://graph.facebook.com/#{current_user.uid}/picture?type=square"}/
      .mybox
        = form_tag project_comments_path(@project.id), :remote => true do
          .textarea-wrapper
            %textarea{name: 'comment[content]'}
            = hidden_field :comment, :commentable_id, :value => @project.id
            = hidden_field :comment, :commentable_type, :value => "Project"
            .actions
              %div{:style => "float:right"}
                %input{:type => :submit, :class => :send}

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.label "Image"
    = f.file_field :avatar
    = f.association :users

  .form-actions
    = f.button :submit

app/views/projects/_storylistitem.html.haml
%li.list-group-item
  .row
    .col-xs-3.col-md-3
      %img.img-responsive{:alt => "", :src => story.avatar.url(:thumb)}/
    .col-xs-9.col-md-9
      %div
        %a{:href => polymorphic_path(story)}
          = story.title
        .mic-info
          On
          = story.created_at
      .comment-text
        = story.description
      .action
        = link_to polymorphic_path(story), options = {remote: true}, html_options={:class => "btn btn-primary btn-xs"} do
          %span.fa.fa-eye
        %a.btn.btn-primary.btn-xs{:title => "Edit", :type => "button", :href => "/stories/#{story.id}/edit" }
          %span.glyphicon.glyphicon-pencil
        %a.btn.btn-danger.btn-xs{:title => "Delete", :type => "button", :href => "/stories/#{story.id}", "data-method" => "delete"}
          %span.glyphicon.glyphicon-trash

         

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

.container
  .row
    .col-xs-12.col-sm-offset-2.col-sm-8{:class => "[ ]"}
      %ul.event-list
        - @projects.each do |project|
          %li
            %time{:datetime => project.created_at}
              %span.day
                = project.created_at.strftime("%d")
              %span.month
                = project.created_at.strftime("%b")
              %span.year
                = project.created_at.strftime("%Y")
              %span.time 8:00 PM
            %img{:alt => "My 24th Birthday!", :src => project.image_url}/
            .info
              %h2.title
                = project.title
              %p.desc
                = project.description
                
                %hr
                - if project.users.empty? == false
                  &nbsp;&nbsp;&nbsp;&nbsp;Members&nbsp;:&nbsp;

                - project.users.each do |user|
                  %span{:class =>"label label-success"}
                    = user.name
                  &nbsp; &nbsp; 
                %br
                %br
                - if project.stories.empty? == false
                  &nbsp;&nbsp;&nbsp;&nbsp;Stories&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;
                - project.stories.each do |story|
                  %span{:class =>"label label-primary"}
                    = story.title
                
              %ul
                %li{:style => "width:33%;"}
                  %a{:href => "/stories/new"}
                    %span.fa.fa-th-list
                    Add Story

                %li{:style => "width:33%;"}
                  %a{:href => "/stories/new"}  
                    %span.fa.fa-male
                    Add Members
                %li{:style => "width:33%;"}

                    

            .social
              %ul
                %li{:style => "width:33%;"}
                  %a{:href=> "/projects/#{project.id}"}               
                    %span.fa.fa-eye
                %li{:style => "width:33%;"}
                  %a{:href => "/projects/#{project.id}/edit"}
                    %span.fa.fa-edit
                %li.google-plus{:style => "width:33%;"}
                  %a{:href => "/projects/#{project.id}", "data-method" => "delete" }
                    %span.fa.fa-trash-o

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', "profiles/#{current_user.id}"

app/views/projects/show.html.haml
%container
  .row.user-menu-container.square
    .col-md-12.user-details
      .row.coralbg.white
        .col-md-9.no-pad
          .user-pad
            %h3
              #{@project.title}
            %h4.white
              %i.fa.fa-check-circle-o
              #{@project.description}
            %a.btn.btn-labeled.btn-info{:href => edit_project_path(@project), :type => "button"}
              %span.btn-label>
                %i.fa.fa-pencil
              Edit
            %a.btn.btn-labeled.btn-info{:href => new_story_path(:project_id => @project.id), :type => "button"}
              %span.btn-label>
                %i.fa.fa-pencil
              New Story
        .col-md-3.no-pad
          .user-image
            %img.img-responsive.thumbnail{:src => @project.avatar.url }/
      .row.overview
        .col-md-4.user-pad.text-center
          %h3 Stories
          %h4
            = @project.stories.count
        .col-md-4.user-pad.text-center
          %h3 Tasks
          %h4 15
        .col-md-4.user-pad.text-center
          %h3 Members
          %h4
            = @project.users.count
  .container.container-xs-height
    .row.row-xs-height
      .col-xs-4.col-xs-height
        .row
          .panel.panel-default.widget
            .panel-heading
              %span.glyphicon.glyphicon-edit
              %h3.panel-title
                Todo
            .panel-body
              %ul.list-group
                - @project.stories.each do |story|
                  - if story.todo?
                    =render 'storylistitem', :story => story
      .col-xs-4.col-xs-height
        .row
          .panel.panel-default.widget
            .panel-heading
              %span.glyphicon.glyphicon-share
              %h3.panel-title
                Doing
            .panel-body
              %ul.list-group
                - @project.stories.each do |story|
                  - if story.doing?
                    =render 'storylistitem', :story => story
      .col-xs-4.col-xs-height
        .row
          .panel.panel-default.widget
            .panel-heading
              %span.glyphicon.glyphicon-check
              %h3.panel-title
                Done
            .panel-body
              %ul.list-group
                - @project.stories.each do |story|
                  - if story.state_cd == 2
                    =render 'storylistitem', :story => story
  .container
    .row
      = render 'comments'
   



= link_to 'Back', projects_path
    