config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  resources :stories do
  	resources :comments
  end

  resources :projects do
  	resources :comments
  end
  
  get '/profiles/:id', to: 'profiles#view', :as => :profiles_view

  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'


end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :project
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  as_enum :state, todo: 0, doing: 1, done: 2
  validates :title, presence: true
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /stories/new
  def new
    @story = Story.new
    @project_id = params[:project_id]
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story.project, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story.project, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:avatar, :title, :image_url, :file_url, :description, :project_id, :state)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.haml
= simple_form_for(@story) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.label "Image"
    = f.file_field :avatar
    = hidden_field :story, :state, :value => :todo
    = hidden_field :story, :project_id, :value => @project_id
  .form-actions
    = f.button :submit

app/views/stories/_storymodal.html.haml
.modal.fade#mymodal
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4.modal-title 
          Story #
          = story.id
      .modal-body
        .row
          .col-lg-12
            .media
              %a.pull-left{:href => "#"}
                %img.media-object.dp.img-circle{:src => "#{story.avatar.url}", :style => "width: 100px;height:100px;"}/
              .media-body
                %h4.media-heading
                  = story.title
                %h5
                  = story.description
                %hr{:style => "margin:8px auto"}
                  - story.project.users.each do |user|
                    %span.label.label-default
                      = user.name
                    &nbsp;

        #container.row
          #header To Do List
          #pending.task-list.task-container
            %h3 Pending
          #inProgress.task-list.task-container
            %h3 In Progress
          #completed.task-list.task-container
            %h3 Completed
          .task-list
            %h3 Add a task
            %form#todo-form
              %input{:placeholder => "Title", :type => "text"}/
              %textarea{:placeholder => "Description"}
              %input#datepicker{:placeholder => "Due Date (dd/mm/yyyy)", :type => "text"}/
              %input.btn.btn-primary{:onclick => "todo.add(#{story.id});", :type => "button", :value => "Add Task"}
            #delete-div
              Drag Here to Delete
          %div{:style => "clear:both;"}
          :javascript
            $( "#datepicker" ).datepicker();
            $( "#datepicker" ).datepicker("option", "dateFormat", "dd/mm/yy");
            $(".task-container").droppable();
            $(".todo-task").draggable({ revert: "valid", revertDuration:200 });
            todo.init(
            {
            "story_id": "#{story.id}"
            });      
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/stories/edit.html.haml
%h1 Editing story

= simple_form_for(@story) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.label "State"
    .br
    = f.select :state, enum_option_pairs(Story, :state)

  .form-actions
    = f.button :submit

= link_to 'Back', stories_path

app/views/stories/index.html.haml
%h1 Listing stories

%table
  %tr
    %th Title
    %th Image url
    %th File url
    %th Description
    %th Project
    %th
    %th
    %th

  - @stories.each do |story|
    %tr
      %td= story.title
      %td= story.image_url
      %td= story.file_url
      %td= story.description
      %td= story.project
      %td= link_to 'Show', story
      %td= link_to 'Edit', edit_story_path(story)
      %td= link_to 'Destroy', story, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Story', new_story_path

app/views/stories/new.html.haml
%h1 New story

= render 'form'

= link_to 'Back', stories_path

app/views/stories/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @story.title
%p
  %b Image url:
  = @story.image_url
%p
  %b File url:
  = @story.file_url
%p
  %b Description:
  = @story.description
%p
  %b Project:
  = @story.project

= link_to 'Edit', edit_story_path(@story)
\|
= link_to 'Back', stories_path

app/views/stories/show.js.haml
var modal = "#{escape_javascript render('stories/storymodal', story: @story)}";

$('body').append(modal);

$('#mymodal').show();
$('#mymodal').modal();

$('#mymodal').on('hidden', function(){ console.log("hidden"); $('#mymodal').remove(); });